//! Does generated code resolve `queuey-core` for the manifest shapes a
//! downstream crate can actually have?
//!
//! `proc-macro-crate` answers from the *consuming* crate's `Cargo.toml`, so this
//! is not something a `trybuild` case can express: every case in `tests/ui`
//! shares this crate's manifest. The regression that made this test exist is a
//! crate with `queuey-core` in `[dependencies]` and `queuey` in
//! `[dev-dependencies]`, which used to be handed `::queuey::__core` for its own
//! lib and fail to compile with ``cannot find `queuey` in the crate root``.
//!
//! The precedence table itself is unit tested in `attrs::tests`; this probe is
//! the end-to-end proof that a real cargo build feeds that table the right
//! thing. It writes throwaway crates and shells out to cargo, which is slow and
//! wants the registry, so it is opt-in:
//!
//! ```sh
//! QUEUEY_PATH_PROBE=1 cargo test -p queuey-macros --test crate_path_probe
//! ```
//!
//! Without the variable it early-returns with a skip notice on stderr, the same
//! shape as the `AMQP_URL` broker tests. CI sets it in the `path-probe` job.

use std::path::{Path, PathBuf};
use std::process::Command;

/// Set this to run the probe. Off by default: it builds three crates.
const OPT_IN: &str = "QUEUEY_PATH_PROBE";

/// One dependency shape to build, test and throw away.
struct Shape {
    /// Directory name, and the name in the failure message.
    name: &'static str,
    /// Body of `[dependencies]`, on top of `serde`.
    dependencies: String,
    /// Body of `[dev-dependencies]`.
    dev_dependencies: String,
    /// Crate the probe imports `#[derive(Queues)]` / `#[derive(Job)]` from.
    derives_from: &'static str,
    /// Crate the probe imports the `Job` / `QueueSet` traits from. The derives
    /// resolve their *own* path to the core crate, which is what is under test.
    traits_from: &'static str,
    /// A statement in the integration test that touches the facade, for the
    /// shapes that have one.
    facade_use: &'static str,
}

/// `crates/`, the parent of this crate's directory.
fn crates_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .expect("crates/macros has a parent")
        .to_path_buf()
}

/// Where the probe crates and their shared build artifacts go.
///
/// Under `target/` so `cargo clean` takes them, and shared between the shapes so
/// the dependency tree is built once.
fn scratch() -> PathBuf {
    crates_dir()
        .parent()
        .expect("crates/ has a parent")
        .join("target/tests/crate_path_probe")
}

fn write(path: &Path, contents: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("create probe directory");
    }
    std::fs::write(path, contents).expect("write probe file");
}

/// The derives under test. `DERIVES_FROM` / `TRAITS_FROM` are substituted per
/// shape, because a facade-only crate cannot name `queuey-macros` or
/// `queuey-core` at all.
const LIB_RS: &str = r#"
use serde::{Deserialize, Serialize};
use DERIVES_FROM::{Job, Queues};

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Queues)]
#[queues(prefix = "probe")]
pub enum ProbeQueues {
    #[queue(prefetch = 4, retry(max_attempts = 2, backoff = "fixed", delay = "1s"))]
    Emails,
}

#[derive(Debug, Serialize, Deserialize, Job)]
#[job(queue = ProbeQueues::Emails, retry(max_attempts = 5))]
pub struct SendEmail {
    pub to: String,
}

/// Reaches into the generated impls, so an unresolved core path is a hard error
/// in the *lib* target and not only where the test happens to look.
pub fn queue_name() -> &'static str {
    use TRAITS_FROM::{Job as _, QueueSet as _};
    assert!(SendEmail::NAME.ends_with("SendEmail"), "{}", SendEmail::NAME);
    ProbeQueues::Emails.name()
}
"#;

/// The integration test every shape gets: it exercises the *test* target, which
/// is where a dev-dependency facade is linked and the lib's own dependencies are
/// not the whole story.
const TEST_RS: &str = r#"
#[test]
fn generated_code_resolves_in_the_test_target() {
    FACADE_USE
    assert_eq!(probe::queue_name(), "probe.emails");
}
"#;

/// Build and test one shape, then delete it.
fn probe(shape: &Shape) {
    let dir = scratch().join(shape.name);
    let Shape {
        dependencies,
        dev_dependencies,
        ..
    } = shape;

    write(
        &dir.join("Cargo.toml"),
        &format!(
            "# Generated by crates/macros/tests/crate_path_probe.rs; edit that, not this.\n\
             [workspace]\n\n\
             [package]\n\
             name = \"probe\"\n\
             version = \"0.0.0\"\n\
             edition = \"2024\"\n\
             publish = false\n\n\
             [dependencies]\n\
             serde = {{ version = \"1\", features = [\"derive\"] }}\n\
             {dependencies}\n\
             [dev-dependencies]\n\
             {dev_dependencies}\n"
        ),
    );
    write(
        &dir.join("src/lib.rs"),
        &LIB_RS
            .replace("DERIVES_FROM", shape.derives_from)
            .replace("TRAITS_FROM", shape.traits_from),
    );
    write(
        &dir.join("tests/integration.rs"),
        &TEST_RS.replace("FACADE_USE", shape.facade_use),
    );

    for command in ["build", "test"] {
        let status = Command::new(env!("CARGO"))
            .current_dir(&dir)
            .env("CARGO_TARGET_DIR", scratch().join("target"))
            // Inherited from the outer build and wrong here: the nested cargo
            // must read the probe's manifest, not this crate's.
            .env_remove("CARGO_MANIFEST_DIR")
            .env_remove("CARGO_PKG_NAME")
            .env_remove("CARGO_CRATE_NAME")
            .env_remove("CARGO_MAKEFLAGS")
            .args([command, "--quiet"])
            .status()
            .unwrap_or_else(|err| {
                panic!("could not run cargo {command} for `{}`: {err}", shape.name)
            });
        assert!(
            status.success(),
            "`cargo {command}` failed for the `{}` dependency shape; \
             see the compiler output above",
            shape.name,
        );
    }

    let _ = std::fs::remove_dir_all(&dir);
}

#[test]
fn every_dependency_shape_resolves_the_core_crate() {
    if std::env::var_os(OPT_IN).is_none() {
        eprintln!("skipping crate path probe: set {OPT_IN}=1 to run it (it shells out to cargo)");
        return;
    }
    let crates = crates_dir();
    let crates = crates.display();
    let core_and_macros = format!(
        "queuey-core = {{ path = \"{crates}/core\" }}\n\
         queuey-macros = {{ path = \"{crates}/macros\" }}\n"
    );
    // `default-features = false` keeps `lapin` out of the probe's build: none of
    // this is about the backend.
    let facade = format!("queuey = {{ path = \"{crates}/queuey\", default-features = false }}\n");

    for shape in [
        // The regression: core for the lib, facade for the tests only. Before
        // the core crate was looked up first, the lib did not compile.
        Shape {
            name: "core_with_dev_facade",
            dependencies: core_and_macros.clone(),
            dev_dependencies: facade.clone(),
            derives_from: "queuey_macros",
            traits_from: "queuey_core",
            facade_use: "let _ = queuey::MemoryBackend::new();",
        },
        // Facade only: what most users have, and the only shape that exercises
        // `::queuey::__core`.
        Shape {
            name: "facade_only",
            dependencies: facade.clone(),
            dev_dependencies: String::new(),
            derives_from: "queuey",
            traits_from: "queuey",
            facade_use: "let _ = queuey::MemoryBackend::new();",
        },
        // Core plus macros, no facade anywhere.
        Shape {
            name: "core_only",
            dependencies: core_and_macros.clone(),
            dev_dependencies: String::new(),
            derives_from: "queuey_macros",
            traits_from: "queuey_core",
            facade_use: "",
        },
    ] {
        probe(&shape);
    }
}
